<?php

            return

            $tr = [
'str' => [
'0' => 'POZBĄDŹ SIĘ DODATKOWYCH KILOGRMÓW SZYBKO I ŁATWO',
'1' => 'Kanabialica',
'2' => 'Czy chcesz:',
'3' => 'Być lekką i piękną?',
'4' => 'Otrzymywać więcej uwagi i komplementów?',
'5' => 'Nosić ubrania, które chcesz?',
'6' => 'Zamów Kanabialica i zmień swoje życie na zawsze! Rabat tylko w tym miesiącu! -50%!',
'7' => 'ZAMÓW KANABIALICA',
'8' => 'ZAWIERA NATURALNY EKSTRAKT Z KONOPI (CBD)',
'9' => 'EFEKT SPRAWDZONY KLINICZNIE',
'10' => 'BEZ ZMNIEJSZENIA PIERSI I BEZ OBWISŁEJ SKÓRY',
'11' => 'PRODUKT CERTYFIKOWANY W UNII EUROPEJSKIEJ',
'12' => 'Kanabialica jest rozpracowana dzięki klinikom zdrowego żywienia',
'13' => 'Adam Żebrowski',
'14' => 'ekspert od zdrowego żywienia',
'15' => 'Przez długi czas śledziłem badania CBD, naturalnego wyciągu z konopi bez efektów psychoaktywnych. Wyciąg z konopi obniża poziom kortyzolu we krwi, co normalizuje poziom hormonów. Stres znika, a problem „stagnacji wagi” przepada, waga zaczyna spadać. Ponadto CBD blokuje aktywność receptorów CB1, co doprowadza do naturalnego zmniejszenia apetytu. Kalorie są przekształcane w energię, a tłuszcze się rozszczepiają. Cały naturalny skład Kanabialica pomaga przyspieszyć metabolizm 8–10 razy oraz oczyszcza organizm z toksyn i żużli. Przy kursowym stosowaniu kropli spala się nawet najbardziej problematyczny tłuszcz podskórny, a prawdopodobieństwo powrotu do wagi zanika. W badaniach klinicznych 97% osób straciło 7-14 kg w ciągu miesiąca.',
'16' => 'JAK KANABIALICA ZMIENI TWOJE CIAŁO W CIĄGU 28 DNI?',
'17' => '1-7 dni',
'18' => 'Kanabialica zaczyna działać. Organizm jest stopniowo oczyszczany, usuwa się wszystko niepotrzebne. Trawienie i metabolizm zaczynają się poprawiać. Objętość i waga ciała się zmniejsza.',
'19' => '8-19 dni',
'20' => 'Zaczyna się tworzyć piękna sylwetka. Ogólny stan organizmu się poprawia. Woda przestaje się zatrzymywać. Najbardziej problematyczny tłuszcz podskórny jest rozkładany. Utrata do 6-8 kg.',
'21' => '20-28 dni',
'22' => 'Oczyszczanie i odmładzanie ciała. Trawienie powraca do normy. Utrata do 14 kg, utrwalenie wyniku.',
'23' => 'DLACZEGO KROPLE KANABIALICA SĄ TAK SKUTECZNE?',
'24' => 'EKSTRAKT Z CORDYCEPS',
'25' => 'Zmniejsza apetyt, wzmacnia układ odpornościowy, poprawia samopoczucie',
'26' => 'EKSTRAKT Z KIWANO, RAMBUTANU I CHERYMOI',
'27' => 'Rozszczepia szkodliwe białe lipidy. Poprawia nastrój i dodaje energii. Detoksykacja i oczyszczanie organizmu.',
'28' => 'EKSTRAKTY Z ZIELONEJ HERBATY, ZIELONEJ KAWY I GORZKIEJ POMARAŃCZY',
'29' => 'Przyspieszają metabolizm o 80%, mają silne działanie przeciwutleniające
',
'30' => 'EKSTRAKT Z KONOPI (CBD)',
'31' => 'Skutecznie spala tłuszcz nawet w najbardziej problematycznych miejscach (talia, biodra, brzuch)',
'32' => 'ŁATWO JEST BYĆ IDEALNĄ!',
'33' => 'Rozpuść 25 kropli w szklance wody lub soku',
'34' => 'Stosuj 2 razy dziennie przed posiłkami',
'35' => 'Zalecane leczenie - co najmniej 28 dni',
'36' => 'OPINIE LUDZI, KTÓRZY OSIĄGNĘLI Z KANABIALICA IDEALNE CIAŁO',
'37' => 'Zawsze biorę tylko naturalne leki i suplementy, nie ufam chemii i dlatego dokładnie sprawdzam skład produktów. Na jednym forum miłośników produktów naturalnych widziałam dyskusję na temat Kanabialica i od razu zainteresowałam się tym rozpracowaniem naukowców. Po 30 latach zrezygnowałam ze sportu i zaczęłam przybierać na wadze, ale dzięki Kanabialica mogłam szybko wrócić do formy i schudnąć. To był najważniejszy i najlepszy prezent na moje urodziny. Mój mąż powiedział, że teraz wyglądam na 25 lat. Jestem bardzo szczęśliwa!',
'38' => 'Nie sądziłem, że konopia naprawdę działa. Byłem sceptycznie nastawiony do produktów ziołowych. Ale naukowe uzasadnienie mnie przekonało i postanowiłem zamówić Kanabialica. -14 kg - nigdy wcześniej mi się to nie zdarzało. Świetny środek! Polecam wszystkim.',
'39' => 'Po 50 latach zaczęłam odczuwać, że przybieram na wadze i że moja skóra zaczyna się pogarszać. A menopauza stała się dla mnie najstraszniejszym stresem w moim życiu. Wpadłam w depresję i utknęłam z nią tak bardzo, jak tylko mogłam. Mój lekarz zalecił terapię fitoestrogenową dla zdrowia kobiet i powiedział mi o Kanabialica. Krople te zawierają wyłącznie naturalne składniki - ekstrakty roślinne, owoce i kompleksy witaminowe. Ekstrakt z konopi jako składnik środku jest nieszkodliwy i normalizuje mój „leniwy” metabolizm. Tak szybko nie spodziewałam się rezultatu! Wszystko się zmieniło, kiedy zaczęłam brać Kanabialica - schudłam 16 kg i czuję się znacznie lepiej, stałam się bardziej zrelaksowana i szczęśliwa.',
'40' => 'UWAGA! OSTRZEGAJ SIĘ PODRÓBEK!',
'41' => 'Ponieważ krople Kanabialica stają się bardzo popularne na rynku europejskim, istnieje wiele podróbek tego produktu. Podróbki oferowane są w niskiej cenie i zawierają zakazane i niebezpieczne chemikalia. Oryginalne krople KANABIALICA (z naturalnym ekstraktem z konopi) są dostępne tylko na naszej stronie internetowej! Nie oszczędzaj na swoim zdrowiu! Zamów certyfikowany produkt Kanabialica od autoryzowanych przedstawicieli w Polsce; Czechach,
Austrii i Szwajcarii!',
'42' => '25 KROPLI - I KAŻDY ZAUWAŻY TWOJE WYNIKI I IDEALNE CIAŁO!',
'43' => 'Dzięki Kanabialica będziesz mogła:',
'44' => '- nosić ubrania o 2-3 rozmiary mniejsze',
'45' => '- otrzymywać więcej uwagi i komplementów',
'46' => '- być szczupłą i zdrową',
'47' => 'Całkowity koszt:',
'48' => 'Cena promocyjna:',
'49' => 'Wpisz swoje imię',
'50' => 'Wpisz swój numer telefonu',
'51' => 'ZAMÓW TERAZ!',
'52' => 'Płatność tylko po otrzymaniu zamówienia',
'53' => 'Polityka prywatności',
'54' => 'Nie wahaj się! Zamów Kanabialica teraz i uzyskaj 50% zniżki',
],
'block' => [
'b0' => [
'0' => 'Zdobądź to',
'1' => 'idealne ciało!',
],
'b1' => [
'0' => 'Gwarantujemy',
'1' => '100% ochronę danych',
],
'b2' => [
'0' => 'Marta 32 lata,',
'1' => 'do 81 kg, po 64 kg',
],
'b3' => [
'0' => 'Oskar, 44 lata,',
'1' => 'do 94 kg, po 80 kg',
],
'b4' => [
'0' => 'Monika, 55 lat,',
'1' => 'do 85 kg, po 69 kg',
],
'b5' => [
'0' => 'OFERTA SPECJALNA',
'1' => 'W TYM MIESIĄCU! -50%',
],
],
];
